apiVersion: formance.com/v1beta1
kind: VersionManifest
metadata:
  name: auth-v1-x
  labels:
    formance.com/component: auth
    formance.com/generation: v1
spec:
  component: auth
  versionRange: "<v2.0.0-rc.5"

  migration:
    enabled: false

  architecture:
    type: stateless
    deployments:
      - name: "auth"
        replicas: "auto"
        stateful: false
        containers:
          - name: "auth"
            ports:
              - name: "http"
                port: 8080
            healthCheck:
              path: "/_healthcheck"
              type: "http"
            environment:
              - name: "CONFIG"
                value: "/config/config.yaml"
            conditionalEnvironment:
              # Base URL configuration
              - when: "settings.auth.base-url != ''"
                env:
                  - name: "BASE_URL"
                    valueFrom:
                      settingKey: "auth.base-url"

              # Signing key from spec or secret
              - when: "spec.signing-key != ''"
                env:
                  - name: "SIGNING_KEY"
                    value: "$(AUTH_SIGNING_KEY)"

  features:
    requiresDatabase: true
    requiresConfiguration: true
    isOAuthProvider: true

  gateway:
    enabled: true
    healthCheckEndpoint: "_healthcheck"

  authorization:
    scopes:
      - name: "auth:admin"
        description: "Manage authentication configuration"
        since: "v1.0.0"

      - name: "auth:clients:read"
        description: "Read OAuth clients"
        since: "v1.0.0"

      - name: "auth:clients:write"
        description: "Manage OAuth clients"
        since: "v1.0.0"