apiVersion: formance.com/v1beta1
kind: VersionManifest
metadata:
  name: payments-v0-9
  labels:
    formance.com/component: payments
    formance.com/generation: v0
    formance.com/architecture: legacy-full
spec:
  component: payments
  versionRange: "<v1.0.0-alpha"

  streams:
    ingestion: "streams/payments"

  migration:
    enabled: true
    strategy: "strict"

  architecture:
    type: stateless
    deployments:
      - name: "payments"
        replicas: "auto"
        stateful: false
        containers:
          - name: "api"
            args: ["serve"]
            ports:
              - name: "http"
                port: 8080
            healthCheck:
              path: "/_health"
              type: "http"
            environment:
              - name: "POSTGRES_DATABASE_NAME"
                value: "$(POSTGRES_DATABASE)"
              - name: "CONFIG_ENCRYPTION_KEY"
                valueFrom:
                  settingKey: "payments.encryption-key"

  features:
    broker: false
    temporal: false

  gateway:
    enabled: true
    healthCheckEndpoint: "_health"

  authorization:
    scopes:
      - name: "payments:read"
        description: "Read payments, accounts, and transactions"
        since: "v0.1.0"

      - name: "payments:write"
        description: "Create and manage payments"
        since: "v0.1.0"

      - name: "payments:connectors:read"
        description: "Read payment connectors configuration"
        since: "v0.1.0"

      - name: "payments:connectors:write"
        description: "Manage payment connectors"
        since: "v0.1.0"