apiVersion: formance.com/v1beta1
kind: VersionManifest
metadata:
  name: webhooks-v2-x
  labels:
    formance.com/component: webhooks
    formance.com/generation: v2
spec:
  component: webhooks
  versionRange: ">=v2.0.0-rc.5"
  extends: ">=v0.7.1 <v2.0.0-rc.5"

  migration:
    enabled: true
    strategy: "strict"

  architecture:
    type: stateless
    deployments:
      # Single deployment with embedded worker
      - name: "webhooks"
        replicas: "auto"
        stateful: false
        containers:
          - name: "api"
            args: ["serve"]
            ports:
              - name: "http"
                port: 8080
            healthCheck:
              path: "/_healthcheck"
              type: "http"
            environment:
              - name: "STORAGE_POSTGRES_CONN_STRING"
                value: "$(POSTGRES_URI)"
              - name: "WORKER"
                value: "true"

  features:
    requiresDatabase: true
    requiresBroker: true
    consumerAllServices: true

  gateway:
    enabled: true
    healthCheckEndpoint: "_healthcheck"

  authorization:
    scopes:
      # Inherit all v0.x scopes
      # (v2 is just a migration improvement, no new API features)