apiVersion: formance.com/v1beta1
kind: VersionManifest
metadata:
  name: webhooks-v0-7-v1-x
  labels:
    formance.com/component: webhooks
    formance.com/generation: v0
    formance.com/architecture: single-deployment
spec:
  component: webhooks
  versionRange: ">=v0.7.1 <v2.0.0-rc.5"
  extends: "<v0.7.1"

  migration:
    enabled: false

  architecture:
    type: stateless
    deployments:
      # Single deployment with embedded worker
      - name: "webhooks"
        replicas: "auto"
        stateful: false
        containers:
          - name: "api"
            args: ["serve"]
            ports:
              - name: "http"
                port: 8080
            healthCheck:
              path: "/_healthcheck"
              type: "http"
            environment:
              - name: "STORAGE_POSTGRES_CONN_STRING"
                value: "$(POSTGRES_URI)"
              - name: "WORKER"
                value: "true"

    # Cleanup old dual deployment
    cleanup:
      deployments: ["webhooks-worker"]
      reason: "Migrating from dual deployment to single deployment with embedded worker"

  features:
    requiresDatabase: true
    requiresBroker: true
    consumerAllServices: true

  gateway:
    enabled: true
    healthCheckEndpoint: "_healthcheck"

  authorization:
    scopes:
      # Inherit all v0.x scopes