apiVersion: stack.formance.com/v1beta1
kind: Stack
metadata:
  name: maxence
spec:
  version: v1.8.0
  namespace: default
  auth:
    type: oauth
  monitoring:
    traces:
      enabled: true
      otlp:
        enabled: true
        endpoint: $(ENDPOINT_IP):4317
        insecure: true
        mode: grpc
  services:
    control:
      scaling:
        enabled: true
        minReplica: 1
        maxReplica: 10
        cpuLimit: 60
    ledger:
      scaling:
        enabled: true
        minReplica: 1
        maxReplica: 10
        cpuLimit: 60
      databases:
        - type: postgresql
          url: postgresql://formance:formance@localhost:5432/formance
        - type: redis
          url: redis://localhost:6379/0
---
apiVersion: stack.formance.com/v1beta1
kind: License
metadata:
  name: maxence
spec:
  licenceId: maxence