---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
spec:
  headers:
    accessControlAllowOriginList:
    - "*"
    accessControlAllowHeaders:
    - "Authorization"
    - "content-type"
    accessControlAllowMethods:
    - "*"
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
    - /api/auth
    - /api/dex
    - /api/jaeger
    - /api/ledger
---
apiVersion: stack.formance.com/v1beta1
kind: Stack
metadata:
  name: stack1
spec:
  namespace: stack1
  debug: true
  scheme: http
  host: kubernetes.docker.internal
  # Define global ingress configuration
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd, default-cors-all@kubernetescrd
  auth:
    image: ghcr.io/numary/auth:a2d200a8d89fcab9e294f58b361443571ee7e7aa
    host: kubernetes.docker.internal
    scheme: http
    delegatedOIDCServer:
      issuer: http://kubernetes.docker.internal/dex
      clientID: dexclient
      clientSecret: dexclient
    postgres:
      host: postgresql.default.svc.cluster.local
      port: 5432
      username: formance
      password: formance
  monitoring:
    traces:
      otlp:
        endpoint:
          value: otel-collector-opentelemetry-collector.default.svc.cluster.local
        insecure: true
        mode: grpc
        port: 4317
  kafka:
    brokers:
    - redpanda.default.svc.cluster.local:9092
  services:
    ledger:
      postgres:
        host: postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
      locking:
        strategy: redis
        redis:
          uri: redis://redis-headless.default.svc.cluster.local:6379
    payments:
      mongoDB:
        host: mongodb-svc.default.svc.cluster.local
        port: 27017
        username: root
        password: very-secured-password
    search:
      elasticSearch:
        host: elasticsearch-master.default.svc.cluster.local
        port: 9200
        scheme: http
        basicAuth:
          username: admin
          password: admin
    control:
      image: ghcr.io/numary/control:cdbeb8e9bd10d388674da80622a113519f1147ce
---
apiVersion: auth.components.formance.com/v1beta1
kind: Scope
metadata:
  name: scope1
  namespace: stack1
spec:
  label: scope1
  authServerReference: auth
#---
#apiVersion: auth.components.formance.com/v1beta1
#kind: Client
#metadata:
#  name: postman
#  namespace: stack1
#spec:
#  public: true
#  authServerReference: auth
#  redirectUris:
#  - https://oauth.pstmn.io/v1/callback
