---
apiVersion: stack.formance.com/v1beta1
kind: Stack
metadata:
  name: stack1
spec:
  version: v1.8.0
  namespace: stack1
  host: kubernetes.docker.internal
  scheme: http
  debug: true
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd
  auth:
    image: ghcr.io/numary/auth:a2d200a8d89fcab9e294f58b361443571ee7e7aa
    delegatedOIDCServer:
      issuer: http://kubernetes.docker.internal/dex
      clientID: dexclient
      clientSecret: dexclient
    postgres:
      host: postgresql.default.svc.cluster.local
      port: 5432
      username: formance
      password: formance
      database: formance
    signingKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAth3atoCXldJgHH9EWnZQMvw5O+vVNKMcvrllEGQsLxvIA5xy
      YPnFt2xU7k1dcN5ViBqPiigVHZNeyyHcdVclg26zqjEwYUqH+OPiRFeBn0SwOG+d
      ZLpOIJdKt7OjmUG0xN9egq81dbPVPBPckuWqB9XMWmM+dtqydBX4lekj+Q1hFn5E
      WXXuAs9aLIc8DzPz8B+oqwLKZ6k6kC5vpj+EaBt8ExVywrWftkWewGWRO7fLw0Fj
      7hamaA1ZTYEqCN+MLDLEd6qmtC2cdgVhZM0RG2OnTiq5lGzNFmLXGOsquc35HSQj
      OQqcLL+e/72K3giJ1YCqYWAIIJcc/kNKU8HtpwIDAQABAoIBAFY+dSEQbLjq09Er
      A/fDJ9+9Sm1yFZnD1Q0NRysoBTSZ93KeWBxMrLFcgCwKP0IASIkX6voGWVmUPMP9
      2SVIi99eQX9LpBmu7g2T/cdXmW8PXFSdpu/Yur78ZsnwLH2bfDvvfBZvWuXOsCCv
      VznJwWfMe+YiMaafkvsenIaBziNWwUeVGHCWl5f++KGGbWFZjhkRZyjKWfMYflig
      EG5e+WaXagCjTah5pUkmvLj3jmB1iGA/Askm8S5QyTt6Z+SIEk+i5T3qCiLFNvzp
      7OeSyfbmWWzBYTiSvEoHhaHfdeicUyOpRthc33bb7LnfIWDG3Z+WE0o6U1nR8o7U
      t5dsj2ECgYEA7SEuBpd/3wdNVLQSI/RHKKO3sdlymh7yRFf7OAn/UxnSJbSNx4y4
      GAEdJD9KwSQlyekLITF+xc0IuyFHOmvuzp1+/LxK/QTY4dcdlwl/r1kmwBbTeR0e
      yl9RtulHXmP+Ss/PZgwR081Lk7zlRkh1busyAOmCE4mJW/IvNBze0dsCgYEAxJvy
      PcbaLVk497U9cUGznsSbbsyq7JGLkBgTu3eQ/yRgoE7pvagF7dV1gQGuCYjOaYml
      U4d95FLPoiE+CE0g2uyouFEsD1UhggTADP33BidUKUcF1ub9VVNcWs4I5LeWPY/X
      5vcpOCAkmRZWT5rieAECdIsfRTnePVyn2L7amyUCgYEAqsZAfWLSJm791Eiy383n
      CW+OtbjiffhXhbzPIbaheNmZrKnxiYrgcfkrYZVrYtmDlXwOFeOtZwqYhRwcTgi5
      PXfTonSAlOPOxibEGqgumrvb2m8V8Z11NU2cbdxnF6Vv17T9qoJ6vEyXZ1iczhcU
      68LaiimhEiz1DZDHSgKYvg0CgYEAjVZyQXjXVWxjqKdQ4T9TKhq6hl95rJFA3DiC
      zuy4fsKe9/9ixyWoBX7DdxdHDrGbeYErKa4okV/6xdnR51PS/67L55zq6KbRbM+P
      ZIeZ8oGJXhchmoj5q0I/DUQ6Xnmf9ueWVQJvTlrFFIxbReTZU12ebzuoIjLkkgYu
      34DsVEUCgYEAtHm/aO7/2UJT40PMO+VDvBCEixPtt6j72fLaW8btgVRAnhp9qaWX
      Cv6TRZPe2y6Bbgg4Q3FuF0DMqx6ongFKQAWo3DkqNFCGRgjJMQ9JbcfOnGySq4U+
      EL/wy5C80pa3jahniqVgO5L6zz0ZLtRIRE7aCtCIu826gctJ1+ShIso=
      -----END RSA PRIVATE KEY-----
  monitoring:
    traces:
      otlp:
        endpoint:
          value: otel-collector-opentelemetry-collector.default.svc.cluster.local
        insecure: true
        mode: grpc
        port: 4317
  collector:
    kind: kafka
    kafka:
      brokers:
      - redpanda.default.svc.cluster.local:9092
  services:
    ledger:
      postgres:
        host: postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        database: ledger
        createDatabase: true
---
apiVersion: auth.components.formance.com/v1beta1
kind: Client
metadata:
  name: postman
  namespace: stack1
spec:
  public: true
  authServerReference: auth
  redirectUris:
  - https://oauth.pstmn.io/v1/callback
#  services:
#    control:
#      scaling:
#        enabled: true
#        minReplica: 1
#        maxReplica: 10
#        cpuLimit: 60
#    ledger:
#      port: 3068
#      scaling:
#        enabled: true
#        minReplica: 1
#        maxReplica: 10
#        cpuLimit: 60
#      databases:
#        - type: postgresql
#          url: postgresql://formance:formance@localhost:5432/formance
#        - type: redis
#          url: redis://localhost:6379/0
#---
#apiVersion: stack.formance.com/v1beta1
#kind: License
#metadata:
#  name: maxence
#spec:
#  licenceId: maxence
