kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: formance
nodes:
- role: control-plane
  image: kindest/node:v1.23.12
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 30080
      hostPort: 80
      protocol: TCP
    - containerPort: 30090
      hostPort: 9000
      protocol: TCP
    - containerPort: 30100
      hostPort: 5005
      protocol: TCP
- role: worker
  image: kindest/node:v1.23.12
- role: worker
  image: kindest/node:v1.23.12
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry-docker-registry.registry.svc.cluster.local:5000"]
    endpoint = ["http://registry-docker-registry.registry.svc.cluster.local:5000"]
