kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: formance
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 30080
      hostPort: 80
      protocol: TCP
    - containerPort: 30090
      hostPort: 9000
      protocol: TCP
- role: worker
- role: worker
