version: '3'

vars:
  POSTGRES_USERNAME: formance
  POSTGRES_PASSWORD: formance
  POSTGRES_DATABASE: formance
  POSTGRES_DSN: postgresql://formance:formance@postgresql:5432/formance
  STACK_NAMESPACE: hosting

includes:
  cluster:
    taskfile: ./tasks/cluster.yaml
    dir: .
  resources:
    taskfile: ./tasks/resources.yaml
    dir: .
  operator:
    taskfile: ./tasks/operator.yaml
    dir: .

tasks:
  tests:
    cmds:
    - make test
  lint:
    cmds:
    - golangci-lint run --fix
