# https://taskfile.dev

version: '3'

tasks:
  cluster:create:
    cmds:
      - kind create cluster --config kind.yaml

  build:
    cmds:
      - make manifests
      - make generate
      - make fmt
      - make vet

  local:deploy:
    deps:
      - build
    cmds:
      - kubectl apply --context kind-formance -f config/crd/bases/
      - kubectl apply --context kind-formance -f example.yaml
      - make run