processors:
- json_schema:
    schema: '{"type": "object"}'
- catch:
  - log:
      level: ERROR
      message: "Schema validation failed due to: ${!error()}"
  - bloblang: root = deleted()
- switch:
  - check: this.type == "SAVED_PAYMENT"
    processors:
      - bloblang: |
          map savedPayment {
            root = [{
              "index": {
                "_id": "PAYMENT-%s".format(this.payload.id),
                "_index": "{{ .ElasticSearchIndex }}"
              }
            }, {
              "data": this.payload,
              "indexed": {
                "provider": this.payload.provider,
                "reference": this.payload.reference,
                "scheme": this.payload.scheme,
                "type": this.payload.type,
                "status": this.payload.status,
                "id": this.payload.id,
                "initialAmount": this.payload.initialAmount
              },
              "kind": "PAYMENT",
              "when": this.date
            }]
          }
                        
          root = this.apply("savedPayment")
  - processors:
    - bloblang: |
        root = deleted()
- catch:
  - bloblang: root = deleted()
