apiVersion: operator.formance.com/v1alpha1
kind: VersionManifest
metadata:
  component: ledger
  versionRange: ">=v2.0.0 <v2.2.0"
  description: "Legacy single/multi-writer architecture with NUMARY_ prefix"
  labels:
    generation: "v2"
    architecture: "legacy"

spec:
  envVarPrefix: "NUMARY_"

  streams:
    ingestion: "streams/ledger"
    reindex: "assets/reindex/v1.0.0"

  migration:
    enabled: true
    strategy: "strict"

  architecture:
    type: "single-or-multi-writer"
    deployments:
      - name: "ledger"
        replicas: "auto"
        stateful: true
        containers:
          - name: "ledger"
            ports:
              - name: "http"
                port: 8080
            healthCheck:
              path: "/_healthcheck"
              type: "http"
            environment:
              - name: "SERVER_HTTP_BIND_ADDRESS"
                value: ":8080"
              - name: "STORAGE_DRIVER"
                value: "postgres"
              - name: "STORAGE_POSTGRES_CONN_STRING"
                value: "$(POSTGRES_URI)"
            volumeMounts:
              - name: "config"
                mountPath: "/root/.numary"
                readOnly: false

  features:
    redisLocking: true
    analytics: false
    experimentalExporters: false

  gateway:
    enabled: true
    healthCheckEndpoint: "_healthcheck"