version: '3'

tasks:
  create:
    desc: Create the Kind cluster
    cmds:
    - kind create cluster --config kind.yaml
    - helm repo add twuni https://helm.twun.io
    - >
      helm upgrade registry twuni/docker-registry
      --namespace default
      --create-namespace
      --install
      --set persistence.enabled=true
      --set service.type=NodePort
      --set service.nodePort=30100
    - helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
    - helm upgrade --install --set args={--kubelet-insecure-tls} metrics-server metrics-server/metrics-server --namespace kube-system

  delete:
    desc: Delete the Kind cluster
    cmds:
    - kind delete cluster --name {{.CLUSTER_NAME}}
    vars:
      CLUSTER_NAME:
        sh: cat kind.yaml|yq .name

  apply:
    cmds:
    - |
      cat <<EOF | kubectl apply -f -
      {{.MANIFEST}}
      EOF

  install:
    desc: Create the cluster and install all resources (PostgreSQL, dex...)
    cmds:
    - task: create
    - task: ":resources:install"
