version: '3'

tasks:
  create:
    desc: Create the Kind cluster
    cmds:
    - kind create cluster --config kind.yaml
    - helm repo add twuni https://helm.twun.io
    - >
      helm upgrade registry twuni/docker-registry
      --namespace default
      --create-namespace
      --install
      --set persistence.enabled=true
      --set service.type=NodePort
      --set service.nodePort=30100 

  delete:
    desc: Delete the Kind cluster
    cmds:
    - kind delete cluster --name {{.CLUSTER_NAME}}
    vars:
      CLUSTER_NAME:
        sh: cat kind.yaml|yq .name
