version: '3'

tasks:
  build:
    desc: Build the docker image operator
    cmds:
    - make docker-build IMG=localhost:5005/numary/operator:latest
  push:
    desc: Push the docker image to the local registry
    deps:
    - build
    cmds:
    - make docker-push IMG=localhost:5005/numary/operator:latest
  crd:
    desc: Install CRD in the cluster
    cmds:
    - make generate
    - make manifests
    - make install
  deploy:
    desc: Deploy the operator inside the cluster
    deps:
    - push
    - crd
    cmds:
    - make deploy IMG=localhost:30100/numary/operator:latest
  run:
    desc: Run the operator locally
    deps:
    - crd
    cmds:
    - make run
