version: '3'

includes:
  postgres:
    taskfile: ./resources/postgres.yaml
    dir: .
  traefik:
    taskfile: ./resources/traefik.yaml
    dir: .
  dex:
    taskfile: ./resources/dex.yaml
    dir: .
  otel:
    taskfile: ./resources/otel.yaml
    dir: .
  redpanda:
    taskfile: ./resources/redpanda.yaml
    dir: .
  elasticsearch:
    taskfile: ./resources/elasticsearch.yaml
    dir: .
  mongodb:
    taskfile: ./resources/mongodb.yaml
    dir: .
  redis:
    taskfile: ./resources/redis.yaml
    dir: .

tasks:
  install:
    desc: Install all availables resources (PostgreSQL, dex...)
    cmds:
    - task: postgres:install
    - task: dex:install
    - task: traefik:install
    - task: otel:install
    - task: elasticsearch:install
    - task: redpanda:install
    - task: redis:install
    - task: mongodb:install
