version: '3'

includes:
  postgres:
    taskfile: ./resources/postgres.yaml
    dir: .
  traefik:
    taskfile: ./resources/traefik.yaml
    dir: .
  dex:
    taskfile: ./resources/dex.yaml
    dir: .
  otel:
    taskfile: ./resources/otel.yaml

tasks:
  install:
    desc: Install all availables resources (PostgreSQL, dex...)
    cmds:
    - task: postgres:install
    - task: dex:install
    - task: traefik:install
    - task: otel:install
