---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-stack-formance-com-v1beta1-configuration
  failurePolicy: Fail
  name: vconfiguration.kb.io
  rules:
  - apiGroups:
    - stack.formance.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurations
  sideEffects: None
