version: '3'

vars:
  DATABASE_NAME: dex

tasks:
  install:
    desc: Install a DEX server
    deps:
    - task: ":postgres:database:create"
      vars:
        NAME: "{{.DATABASE_NAME}}"
    cmds:
    - helm repo add dex https://charts.dexidp.io
    - >
      helm upgrade dex dex/dex
      --install
      --set config.issuer="http://kubernetes.docker.internal/api/dex"
      --set config.storage.type=postgres
      --set config.storage.config.host=postgresql
      --set config.storage.config.port=5432
      --set config.storage.config.database={{.DATABASE_NAME}}
      --set config.storage.config.user={{.POSTGRES_USERNAME}}
      --set config.storage.config.password={{.POSTGRES_PASSWORD}}
      --set config.storage.config.ssl.mode=disable
      --set config.enablePasswordDB=true
      --set config.staticPasswords[0].email="admin@formance.com"
      --set config.staticPasswords[0].hash="\$2a\$10\$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      --set config.staticPasswords[0].username="admin"
      --set config.staticPasswords[0].userID="08a8684b-db88-4b73-90a9-3cd1661f5466"
      --set config.staticClients[0].id=dexclient
      --set config.staticClients[0].secret=dexclient
      --set config.staticClients[0].name=dexclient
      --set config.staticClients[0].redirectURIs[0]=http://kubernetes.docker.internal/api/auth/delegatedoidc/callback
      --set ingress.enabled=true
      --set ingress.hosts[0].host=kubernetes.docker.internal
      --set ingress.hosts[0].paths[0].path=/api/dex
      --set ingress.hosts[0].paths[0].pathType=Prefix
