version: '3'

tasks:
  install:
    desc: Install OpenTelemetry stack
    cmds:
    - helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
    - >
      helm upgrade --install --create-namespace otel-collector open-telemetry/opentelemetry-collector
      --set mode=deployment
      --set config.exporters.jaeger.endpoint=jaeger:14250
      --set config.service.pipelines.traces.exporters[0]=jaeger
      --set config.exporters.jaeger.tls.insecure=true
    - task: "::cluster:apply"
      vars:
        MANIFEST: |
          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: jaeger
            labels:
              app: jaeger
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: jaeger
            template:
              metadata:
                labels:
                  app: jaeger
              spec:
                containers:
                - name: jaeger
                  image: jaegertracing/all-in-one:1.29
                  command:
                  - /go/bin/all-in-one-linux
                  - --query.base-path=/jaeger
                  ports:
                  - containerPort: 16686
                  - containerPort: 14250
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: jaeger
          spec:
            selector:
              app: jaeger
            ports:
            - name: http
              protocol: TCP
              port: 16686
              targetPort: 16686
            - name: collector
              protocol: TCP
              port: 14250
              targetPort: 14250
          ---
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: jaeger
          spec:
            rules:
            - host: kubernetes.docker.internal
              http:
                paths:
                - path: /jaeger
                  pathType: Prefix
                  backend:
                    service:
                      name: jaeger
                      port:
                        number: 16686
