version: '3'

tasks:
  install:
    desc: Install PostgreSQL server on default namespace
    cmds:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - >
      helm upgrade postgresql bitnami/postgresql
      --install
      --set architecture=standalone
      --set global.postgresql.auth.postgresPassword={{.POSTGRES_PASSWORD}}
      --set global.postgresql.auth.username={{.POSTGRES_USERNAME}}
      --set global.postgresql.auth.password={{.POSTGRES_PASSWORD}}
      --set global.postgresql.auth.database={{.POSTGRES_DATABASE}}
  uninstall:
    desc: Uninstall PostgreSQL server
    cmds:
    - >
      helm uninstall postgresql
  database:create:
    desc: Create a new postgres database
    cmds:
    - task: "::cluster:apply"
      vars:
        MANIFEST: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: create-database-{{.NAME}}
          spec:
            template:
              spec:
                containers:
                - name: pi
                  image: docker.io/bitnami/postgresql:14.4.0-debian-11-r21
                  command:
                  - sh
                  - -c
                  - psql -Atx {{.POSTGRES_DSN}}/postgres -c "SELECT 1 FROM pg_database WHERE datname = '{{.NAME}}'" | grep -q 1 && echo "Base already exists" || psql -Atx {{.POSTGRES_DSN}} -c "CREATE DATABASE \"{{.NAME}}\""
                restartPolicy: OnFailure
