version: '3'

tasks:
  install:
    desc: Install RedPanda (https://docs.redpanda.com/docs/quickstart/kubernetes-qs-cloud/)
    vars:
      VERSION:
        sh: curl -s https://api.github.com/repos/redpanda-data/redpanda/releases/latest | jq -r .tag_name
    cmds:
      - helm repo add jetstack https://charts.jetstack.io
      - >
        helm upgrade --install cert-manager jetstack/cert-manager
        --version v1.4.4
        --set installCRDs=true
      - helm repo add redpanda https://charts.vectorized.io/
      - helm repo update redpanda
      - kubectl apply -k 'https://github.com/redpanda-data/redpanda/src/go/k8s/config/crd?ref={{.VERSION}}&timeout=600'
      - helm upgrade --dependency-update --install redpanda-operator redpanda/redpanda-operator --version {{.VERSION}}
      # Configure a one node cluster with developer mode
      - task: "::cluster:apply"
        vars:
          MANIFEST: |
            apiVersion: redpanda.vectorized.io/v1alpha1
            kind: Cluster
            metadata:
              name: redpanda
            spec:
              image: "vectorized/redpanda"
              version: "latest"
              replicas: 1
              resources:
                requests:
                  cpu: 1
                  memory: 1.2Gi
                limits:
                  cpu: 1
                  memory: 1.2Gi
              configuration:
                rpcServer:
                  port: 33145
                kafkaApi:
                - port: 9092
                pandaproxyApi:
                - port: 8082
                schemaRegistry:
                  port: 8081
                adminApi:
                - port: 9644
                developerMode: true
      - task: "::cluster:apply"
        vars:
          MANIFEST: |
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: configure-redpanda
            spec:
              template:
                spec:
                  containers:
                  - name: configure-redpanda
                    image: vectorized/redpanda:latest
                    command:
                    - rpk
                    - cluster
                    - config
                    - set
                    - auto_create_topics_enabled
                    - "true"
                    - --api-urls
                    - http://redpanda.default.svc.cluster.local:9644
                  restartPolicy: OnFailure
