# permissions for end users to edit searchingesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: searchingester-editor-role
rules:
- apiGroups:
  - components.formance.com
  resources:
  - searchingesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - searchingesters/status
  verbs:
  - get
