---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.components.formance.com
  resources:
  - clients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.components.formance.com
  resources:
  - clients/finalizers
  verbs:
  - update
- apiGroups:
  - auth.components.formance.com
  resources:
  - clients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auth.components.formance.com
  resources:
  - scopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.components.formance.com
  resources:
  - scopes/finalizers
  verbs:
  - update
- apiGroups:
  - auth.components.formance.com
  resources:
  - scopes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benthos.components.formance.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benthos.components.formance.com
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - benthos.components.formance.com
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benthos.components.formance.com
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benthos.components.formance.com
  resources:
  - streams/finalizers
  verbs:
  - update
- apiGroups:
  - benthos.components.formance.com
  resources:
  - streams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - auths/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - auths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - components.formance.com
  resources:
  - controls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - controls/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - controls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - components.formance.com
  resources:
  - ledgers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - ledgers/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - ledgers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - components.formance.com
  resources:
  - payments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - payments/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - payments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - components.formance.com
  resources:
  - searches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - searches/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - searches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - components.formance.com
  resources:
  - searchingesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - components.formance.com
  resources:
  - searchingesters/finalizers
  verbs:
  - update
- apiGroups:
  - components.formance.com
  resources:
  - searchingesters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
