apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../certmanager/certificate.yaml
  name: serving-cert
  namespace: formance-system
spec:
  dnsNames:
  - webhook-service.formance-system.svc
  - webhook-service.formance-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
