apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../certmanager/certificate.yaml
  name: selfsigned-issuer
  namespace: formance-system
spec:
  selfSigned: {}
