apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../rbac/leader_election_role_binding.yaml
  name: leader-election-rolebinding
  namespace: formance-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: formance-system
