apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    config.kubernetes.io/origin: |
      path: ../rbac/auth_proxy_client_clusterrole.yaml
  name: metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
