apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
        control-plane: formance-controller-manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: formance-controller-manager
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/operator
          args:
            {{- with .Values.operator.metricsAddr }}
            - --metrics-bind-address={{ $.Values.operator.metricsAddr }}
            {{- end }}
            {{- with .Values.operator.probeAddr }}
            - --health-probe-bind-address={{ $.Values.operator.probeAddr }}
            {{- end }}
            {{- with .Values.operator.enableLeaderElection }}
            - --leader-elect
            {{- end }}
            {{- with .Values.operator.env }}
            - --env={{ $.Values.operator.env }}
            {{- end }}
            {{- with .Values.operator.region }}
            - --region={{ $.Values.operator.region }}
            {{- end }}
            {{ if .Values.global.licence.createSecret }}
            - --licence-secret={{ include "operator.fullname" . }}-licence
            {{- else }}
            - --licence-secret={{ .Values.global.licence.existingSecret }}
            {{- end }}
            {{- if .Values.operator.disableWebhooks }}
            - --disable-webhooks
            {{- end }}
            {{ if .Values.operator.utils.tag }}
            - --utils-version={{ .Values.operator.utils.tag }}
            {{- end }}
            {{- if .Values.operator.dev }}
            - --zap-devel
            - Development
            {{- end }}
          ports:
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ regexReplaceAll ":" .Values.operator.probeAddr "" | default "8081" }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ regexReplaceAll ":" .Values.operator.probeAddr "" | default "8081" }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.webhooks.enabled }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webhooks.enabled }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
      {{- end }}
