{{- if and .Values.global.licence.createSecret (eq (len .Values.global.licence.existingSecret) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-licence
  namespace: {{ .Release.Namespace }}
  labels:
    formance.com/stack: any
stringData:
  token: {{ .Values.global.licence.token }}
  issuer: {{ .Values.global.licence.issuer }}
{{- end }}