VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.19.0 AS core

FROM core+base-image

sources:
    FROM core+builder-image
    WORKDIR /src
    WORKDIR /src/components/operator/tools/utils
    COPY --dir cmd .
    COPY go.* main.go .
    SAVE ARTIFACT /src

compile:
    FROM core+builder-image
    COPY (+sources/*) /src
    WORKDIR /src/components/operator/tools/utils
	DO --pass-args core+GO_COMPILE

build-image:
    FROM core+final-image
    ENTRYPOINT ["/usr/bin/operator-utils"]
    COPY --pass-args (+compile/main) /usr/bin/operator-utils
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO --pass-args core+SAVE_IMAGE --COMPONENT=operator-utils --TAG=$tag