name: Release
on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write

jobs:
  GoReleaser:
    runs-on: "shipfox-4vcpu-ubuntu-2404"
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Setup Env
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix --extra-experimental-features "nix-command" --extra-experimental-features "flakes"
          develop --impure --command just release
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}